import { chromium } from 'playwright';
const BASE = 'http://localhost:5185';
const browser = await chromium.launch({ headless: false });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`${BASE}/login`, { waitUntil: 'domcontentloaded' });
await page.locator('input[name="email"]').fill('test@anomalia.so');
await page.locator('input[name="password"]').fill('123456');
await page.locator('form[action="?/login"] button[type="submit"]').click({ timeout: 60_000 });
await page.waitForTimeout(8000);
console.log('url:', page.url());
const formText = await page.locator('form[action="?/login"]').innerText().catch(() => '(form gone)');
console.log('form:', formText.replace(/\n+/g, ' | ').slice(0, 300));
await browser.close();
